### ISSUE TITLE
Inserting over selection

### ISSUE THREAD

**Issue by aldinezi** [icebob/vue-touch-keyboard#39]
Inserting character over selection should behave as hardware keyboard does, replacing selection with pressed character. 

Currently, inserting character over selection just inserts character on the beginign of selection.

I have created PR that expands this behavior. #38

**Comment by stvedo** [comment]
I'm having same issue in my project. This fix would save me a lot of "hacky" work.

**Comment by icebob** [comment]
Released in 0.3.2

**Comment by aldinezi** [comment]
@icebob Thank you!
