### ISSUE TITLE
When will the Vue v2.x be supported?

### ISSUE THREAD

**Issue by xeoshow** [icebob/vue-touch-keyboard#4]
Hello,

Looks very nice keybord for vue, while I am using vuejs 2.0 in production, is there any plan for supportting  v2.0?

Thanks!

**Comment by icebob** [comment]
I'm currently not working on it, but if I have more time I will migrate to vue2.

**Comment by icebob** [comment]
I'm working on. It seems easy to migrate to vue 2

**Comment by icebob** [comment]
Done. Update to v0.2.0 version and use with Vue 2.x
