### ISSUE TITLE
Persian support

### ISSUE THREAD

**Issue by hosein2398** [icebob/vue-touch-keyboard#5]
Hey
Is it OK if I fork and add support for Persian ? 
Do you have specific strategy for supporting other langs?
My suggestion is this syntax :
`data-layout="per_normal"`
`data-layout="pol_normal"`
I think this is the easiest and most appropriate way for supporting other langs. what do you think?

**Comment by icebob** [comment]
Yes, PR is welcome. But currentyl there is no strategy to add other langs. But I'm thinking on it.
